## Application Configuration

server.port=9090
spring.application.name=spring-gateway-filters
spring.config.import=classpath:gateway-config.yml

## Logging Configuration

logging.level.root=info
#logging.level.org.springframework.cloud=debug
logging.level.com.github.pmvieira93=debug


## Custom Configuration

beans.printable=false


## JWT Configs

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJqd3Qtd2ViIiwic3ViIjoiMTIzNDU2Nzg5MCIsImF1ZCI6ImFwaS1nYXRld2F5IiwibmFtZSI6ImZvbyIsImlhdCI6MTUxNjIzOTAyMiwiZXhwIjoxNzYzNzE1ODkxLCJqdGkiOiI5NmM3ZmMyNi1kNjQwLTRmZGYtODlmNi1hYjRkYmJiNmNlYTQifQ.WxDQHjpjCYbtevn6u7RJIkR5grlTTpYjn7W6UqRD5mI

# sign=free; name=foo; sub=1234567890
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJqd3Qtd2ViIiwic3ViIjoiMTIzNDU2Nzg5MCIsInNpZ24iOiJmcmVlIiwiYXVkIjoiYXBpLWdhdGV3YXkiLCJuYW1lIjoiZm9vIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE3NjM3MTU4OTEsImp0aSI6Ijk2YzdmYzI2LWQ2NDAtNGZkZi04OWY2LWFiNGRiYmI2Y2VhNCJ9.7PI33Vcjv8u5vK6X6iJ-Gp4b4AXNZjcUvFMRZaiHUiQ
# sign=premium; name=bar; sub=bar123
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJqd3Qtd2ViIiwic3ViIjoiYmFyMTIzIiwic2lnbiI6InByZW1pdW0iLCJhdWQiOiJhcGktZ2F0ZXdheSIsIm5hbWUiOiJiYXIiLCJpYXQiOjE1MTYyMzkwMjIsImV4cCI6MTc2MzcxNTg5MSwianRpIjoiOTZjN2ZjMjYtZDY0MC00ZmRmLTg5ZjYtYWI0ZGJiYjZjZWE0In0.0WilbbQQee8uKpra5yF2mOvuOJbVrez6GTOBCE-m_MU
# sign=guest; name=john; sub=john909; onbehalfof=bar123
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJqd3Qtd2ViIiwic3ViIjoiam9objkwOSIsInNpZ24iOiJndWVzdCIsImF1ZCI6ImFwaS1nYXRld2F5IiwibmFtZSI6ImpvaG4iLCJvbmJlaGFsZm9mIjoiYmFyMTIzIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE3NjM3MTU4OTEsImp0aSI6Ijk2YzdmYzI2LWQ2NDAtNGZkZi04OWY2LWFiNGRiYmI2Y2VhNCJ9.f08hYjB7mjOUG_y4n4pakwyRagOBqthRplIo9tkJTPc
jwt.security.secret=gateway-spring-verify


## OpenFGA Configs

openfga.api.url=http://localhost:8080
openfga.api.username=dev
openfga.api.password=pwd.dev
openfga.api.token=gateway-api-key-v1
#openfga.api.store.id=store-id
#openfga.api.auth-model.id=authorization-model-id
