## Application Configuration

spring.application.name=spring-gateway-filters
spring.config.import=classpath:gateway-config.yml

## Logging Configuration

logging.level.root=info
#logging.level.org.springframework.cloud=debug
logging.level.com.github.pmvieira93=debug


## Custom Configuration

beans.printable=false


## JWT Configs

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJqd3Qtd2ViIiwic3ViIjoiMTIzNDU2Nzg5MCIsImF1ZCI6ImFwaS1nYXRld2F5IiwibmFtZSI6ImZvbyIsImlhdCI6MTUxNjIzOTAyMiwiZXhwIjoxNzYzNzE1ODkxLCJqdGkiOiI5NmM3ZmMyNi1kNjQwLTRmZGYtODlmNi1hYjRkYmJiNmNlYTQifQ.WxDQHjpjCYbtevn6u7RJIkR5grlTTpYjn7W6UqRD5mI
jwt.security.secret=gateway-spring-verify