#
# Gateway Routes Configurations
#
spring:
  cloud:
    gateway:
      routes:
      - id: httpbin_self_route
        uri: http://httpbin.org
        predicates:
        - Header=X-Request-Id, \d+
        - Path=/self/**
        filters:
        - RewritePath=/self/?(?<segment>.*), /$\{segment}
      
      - id: httpbin_trace_route
        uri: http://httpbin.org
        predicates:
          - Path=/trace/**
        filters:
          - RewritePath=/trace/?(?<segment>.*), /$\{segment}
          - name: TraceRequest
            args:
              baseMessage: "Request to example route"
              details: true
      
      - id: httpbin_apiversionfilter_v1_route
        uri: http://httpbin.org
        predicates:
        - Path=/v1/**
        filters:
        - RewritePath=/v1/?(?<segment>.*), /$\{segment}
        - name: ApiVersionValidation
          args:
            headerName: ApiVersion
      
      - id: httpbin_apiversionfilter_v2_route
        uri: http://httpbin.org
        predicates:
        - Path=/v2/**
        filters:
        - RewritePath=/v2/?(?<segment>.*), /$\{segment}
        - ApiVersionValidation=X-Api-Version

      - id: httpbin_apiversionfilterv2_v1_route
        uri: http://httpbin.org
        predicates:
        - Path=/v1_2/**
        filters:
        - RewritePath=/v1_2/?(?<segment>.*), /$\{segment}
        - name: ApiVersionValidationV2
          args:
            headerName: ApiVersion
            returnStatus: 401
      
      - id: httpbin_apiversionfilterv2_v2_route
        uri: http://httpbin.org
        predicates:
        - Path=/v2_2/**
        filters:
        - RewritePath=/v2_2/?(?<segment>.*), /$\{segment}
        - ApiVersionValidationV2=X-Api-Version, 403 
