#
# Gateway Routes Configurations
#
spring:
  cloud:
    gateway:
      routes:
      - id: yml_header_path_rewrite_route
        uri: http://httpbin.org
        predicates:
        - Header=X-Request-Id, \d+
        - Path=/self/**
        filters:
        - RewritePath=/self/?(?<segment>.*), /$\{segment}
      - id: yml_example_route
        uri: http://httpbin.org
        predicates:
          - Path=/example/**
        filters:
          - RewritePath=/example/?(?<segment>.*), /$\{segment}
          - name: LoggingRequest
            args:
              baseMessage: "Request to example route"
              details: true
      - id: yml_path_rewrite_apiversion_route
        uri: http://httpbin.org
        predicates:
        - Path=/v1/**
        filters:
        - RewritePath=/v1/?(?<segment>.*), /$\{segment}
        - name: ApiVersionValidation
          args:
            headerName: ApiVersion