name: 'Maven Build & Verify'
run-name: 'Maven Build & Verify'

on:
  push:
    branches:
      - master
      - create-action-generate-test-report
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read
  actions: read
  checks: write

env:
  JDK_VERSION: 17
  JDK_DIST: 'temurin'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up JDK ${{ env.JDK_VERSION }} of ${{ env.JDK_DIST }} '
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: ${{ env.JDK_DIST }}

      - name: 'Build with Maven'
        run: mvn --no-transfer-progress -B verify --file pom.xml
        continue-on-error: true

      - name: 'Upload test results'
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
          retention-days: 7

      - name: 'Check Installed Packages'
        run: |
          which python 
          python --version

      - name: 'Generate Test Report'
        run: |
          python java-test-report.py -d -i target/surefire-reports
          cat test-report.md >> $GITHUB_STEP_SUMMARY

      # https://github.com/marketplace/actions/test-reporter
      # Or https://github.com/test-summary/action
      #- name: 'Test Report'
      #  uses: dorny/test-reporter@v1
      #  if: always()
      #  with:
      #    name: java-junit-tests
      #    path: target/surefire-reports/TEST-*.xml
      #    reporter: java-junit
      #    only-summary: '${{ vars.TEST_REPORT_SUMMARY }}'
      #    fail-on-error: 'false'
