name: 'Maven Build & Verify'
run-name: 'Maven Build & Verify'

on:
  push:
    branches:
      - master
      - github-actions-improvement
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read
  actions: read
  checks: write

env:
  JDK_VERSION: 17
  JDK_DIST: 'temurin'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Check Installed tools'
        run: |
          docker --version
          docker compose version 2>&1
          node --version 2>&1
          python --version 2>&1
          npm --version 2>&1
          jq --version 2>&1
          make --version 2>&1

      - name: 'Install Additional Packages'
        run: |
          echo "Install newman from NPM"
          npm install -g newman

      - name: 'Set up JDK ${{ env.JDK_VERSION }} of ${{ env.JDK_DIST }} '
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: ${{ env.JDK_DIST }}

      - name: 'Initialize Dependencies'
        if: ${{ hashFiles('./docker-compose.yaml') != '' }}
        run: |
          # Initializer Docker Services
          docker compose up --build -d
          sleep 10
          newman run fga-initializer.postman_collection.json --export-globals ./target/generated-ids.json
          cat ./target/generated-ids.json | jq
          jq -r '.values | map("\(.key|sub("-";"_"; "g")|ascii_upcase)=\(.value|tostring)")|.[]' ./target/generated-ids.json >> .env
          cat .env

      - name: 'Build with Maven'
        run: mvn --no-transfer-progress -B verify --file pom.xml

      - name: 'Upload test results'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
          retention-days: 7

      - name: 'Generate Test Report'
        if: always()
        run: |
          python .github/java-test-report.py --details --input target/surefire-reports
          cat test-report.md >> $GITHUB_STEP_SUMMARY
